"""
adapter.py -- OpenRAM behind the custom-block contract.

Reads $GRAFUX_IN/<port>, writes an OpenRAM config, runs the compiler, and
publishes its results as $GRAFUX_OUT/<port> (text) and $GRAFUX_OUT/files/*
(artifacts).  It deliberately repeats the native block's rules
(``EDA/flow.py::build_openram_config`` / ``classify_openram_outputs``) so a
custom openram block and a native one produce the same ports -- that parity is
the acceptance test for the generic runner.
"""

import json
import os
import shutil
import subprocess
import sys

IN = os.environ["GRAFUX_IN"]
OUT = os.environ["GRAFUX_OUT"]
WORK = os.environ.get("GRAFUX_WORK", os.getcwd())
RUN_DIR = os.path.join(WORK, "openram_out") + "/"   # OpenRAM joins path+name with NO separator
FILES = os.path.join(OUT, "files")
TRUE = ("1", "true", "yes", "on")


def port(name, default=""):
    try:
        with open(os.path.join(IN, name), encoding="utf-8") as fh:
            v = fh.read().strip()
    except OSError:
        v = ""
    return v or default


def emit(name, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as fh:
        fh.write(text)


def py_list(text, quote):
    items = [t.strip() for t in text.replace(";", ",").split(",") if t.strip()]
    if not items:
        return ""
    return "[" + ", ".join(json.dumps(i) if quote else i for i in items) + "]"


def build_config(tech, name):
    forced = [
        "# --- forced by Grafux: the results are read back from here ---",
        "output_path = " + json.dumps(RUN_DIR),
        "output_name = " + json.dumps(name),
    ]
    override = port("config")
    if override:
        return override.rstrip() + "\n\n" + "\n".join(forced) + "\n"
    lines = ["# Generated by the Grafux custom openram block."]
    for field in ("word_size", "num_words", "num_banks", "num_rw_ports",
                  "num_r_ports", "num_w_ports", "write_size"):
        raw = port(field)
        if raw:
            lines.append("%s = %d" % (field, int(raw)))
    lines.append("tech_name = " + json.dumps(tech))
    corners = py_list(port("process_corners"), True)
    volts = py_list(port("supply_voltages"), False)
    temps = py_list(port("temperatures"), False)
    if corners:
        lines.append("process_corners = " + corners)
    if volts:
        lines.append("supply_voltages = " + volts)
    if temps:
        lines.append("temperatures = " + temps)
    if not (corners or volts or temps):
        lines.append("nominal_corner_only = True")
    lines.append("analytical_delay = True")
    lines.append("check_lvsdrc = %s" % (port("check_lvsdrc").lower() in TRUE))
    if port("netlist_only").lower() in TRUE:
        lines.append("netlist_only = True")
    lines.extend(forced)
    extra = port("extra_config")
    if extra:
        lines += ["", "# --- extra_config port ---", extra]
    return "\n".join(lines) + "\n"


def classify(names, name):
    """Per extension: exact <name><ext>, then startswith(<name>), then largest."""
    by_size = sorted(names, key=lambda n: -os.path.getsize(os.path.join(RUN_DIR, n)))
    found = {}
    for ext in (".gds", ".lef", ".lib", ".sp", ".v", ".html", ".py"):
        cands = [n for n in by_size if n.endswith(ext)]
        pick = next((n for n in cands if n == name + ext), None) \
            or next((n for n in cands if n.startswith(name)), None) \
            or (cands[0] if cands else None)
        if pick:
            found[ext] = pick
    return found


def main():
    tech = port("tech_name", "scn4m_subm")
    name = port("output_name", "sram")
    cfg = build_config(tech, name)
    os.makedirs(RUN_DIR, exist_ok=True)
    os.makedirs(FILES, exist_ok=True)
    cfg_path = os.path.join(WORK, "openram_config.py")
    with open(cfg_path, "w", encoding="utf-8") as fh:
        fh.write(cfg)
    emit("top", name)
    emit("tech_name", tech)
    emit("config", cfg)

    home = os.environ.get("OPENRAM_HOME", "/opt/openram/compiler")
    cmd = [sys.executable, os.path.join(home, "..", "sram_compiler.py"), cfg_path]
    rc = subprocess.call(cmd, cwd=WORK)

    names = [n for n in os.listdir(RUN_DIR) if os.path.isfile(os.path.join(RUN_DIR, n))]
    found = classify(names, name)
    for ext in (".gds", ".lef", ".lib", ".sp", ".html"):
        if ext in found:
            shutil.copy(os.path.join(RUN_DIR, found[ext]), os.path.join(FILES, found[ext]))
    if ".v" in found:
        with open(os.path.join(RUN_DIR, found[".v"]), encoding="utf-8", errors="replace") as fh:
            emit("verilog_model", fh.read())
    if ".py" in found:
        with open(os.path.join(RUN_DIR, found[".py"]), encoding="utf-8", errors="replace") as fh:
            emit("config", fh.read())
    emit("stats", json.dumps({
        "tech_name": tech, "output_name": name,
        "word_size": port("word_size"), "num_words": port("num_words"),
        "views": sorted(ext.lstrip(".") for ext in found),
    }))
    if rc != 0:
        emit("errors", "OpenRAM exited with code %d; the log port has its output." % rc)
    elif ".gds" not in found and port("netlist_only").lower() not in TRUE:
        emit("errors", "OpenRAM finished without producing a macro. The commonest causes are a "
                       "tech_name the image does not carry and a parameter combination the "
                       "technology cannot build.")
    return rc


if __name__ == "__main__":
    sys.exit(main())
